version: "2.2"
services:
  eureka-server:
    container_name: eureka-server
    image: josuaramouche/real_vs_ai-discovery_ms:latest
    ports:
      - "8761:8761"
    networks:
      project-network:
        ipv4_address: 172.19.0.10

  model-ct:
    container_name: model-ct
    image: josuaramouche/real_vs_ai-model_ms:latest
    ports:
      - "8090:8090"
    depends_on:
      - eureka-server
    restart: on-failure
    networks:
      project-network:
        ipv4_address: 172.19.0.11

  prediction-ct:
    container_name: prediction-ct
    image: josuaramouche/real_vs_ai-prediction_ms:latest
    ports:
      - "8081:8081"
    depends_on:
      - model-ct
    restart: on-failure
    networks:
      project-network:
        ipv4_address: 172.19.0.12

  api-gateway-ct:
    container_name: api-gateway-ct
    image: josuaramouche/real_vs_ai-api_gateway_ms:latest
    ports:
      - "50000:8080"
    depends_on:
      - model-ct
    restart: on-failure
    networks:
      project-network:
        ipv4_address: 172.19.0.13

networks:
  project-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
