import React from "react";
import { Card, CardContent, Typography } from "@mui/material";
import { FcAnswers, FcApproval, FcHighPriority } from "react-icons/fc";

interface DisplayCardProps {
  result: string | null;
  accuracy: string | null;
}

interface ResultContent {
  title: string;
  icon: JSX.Element;
  description: string;
  precision: string;
}

const DisplayCard: React.FC<DisplayCardProps> = ({ result, accuracy }) => {
  const getResultContent = (): ResultContent => {
    if (result === "NOT GENERATED BY AI") {
      return {
        title: "Result of the analysis",
        icon: <FcApproval />,
        description: "Image not generated by an AI",
        precision: `Accuracy or the result : ${accuracy}%`,
      };
    } else if (result === "GENERATED BY AI") {
      return {
        title: "Result of the analysis",
        icon: <FcHighPriority />,
        description: "Image generated by an AI",
        precision: `Accuracy or the result : ${accuracy}%`,
      };
    } else {
      console.error("Erreur : Le modèle n'a pas fourni de résultat");
      return {
        title: "Error",
        icon: <FcAnswers />,
        description: "We are sorry, the analyse failed",
        precision: `Accuracy or the result : ${accuracy}%`,
      };
    }
  };

  const content = getResultContent();

  return (
    <Card style={{backgroundColor: "#CFEFDA"}}>
      <CardContent>
        <Typography gutterBottom sx={{ color: "text.secondary", fontSize: 14 }}>
          {content.title}
        </Typography>
        <Typography variant="h6" component="div" sx={{fontWeight: 'bold'}}>
        {content.description} {content.icon}
        </Typography>
        <Typography variant="h6" component="div" sx={{fontSize: 16}}>
        {content.precision}
        </Typography>
      </CardContent>
    </Card>
  );
};

export default DisplayCard;
