import { FileUploader } from "react-drag-drop-files";
import "./Page.css";
import { useState } from "react";
import { Button } from "@mui/material";
import { useNavigate } from "react-router-dom";

const fileTypes = ["JPG", "PNG", "WEBP"];

const Page: React.FC = () => {  
  const [file, setFile] = useState<File | null>(null);
  const [disableButton, setDisableButton] = useState(true);
  const [fileURL, setFileURL] = useState<string | null>(null);
  const navigate = useNavigate();
  const r = null;
  const a = null;

  // Gestion du changement de fichier
  const handleChange = (file: File) => {
    setFile(file);
    setDisableButton(!file);
    if (file) {
      const imageUrl = URL.createObjectURL(file);
      setFileURL(imageUrl);
    } else {
      setFileURL(null);
    }
  };

  const handleNavigateToResults = () => {
    if (file && fileURL) {
      navigate('/results', {
        state: { file, fileURL, r, a },
      });
    }
  };

  return (
    <div className="page">
      <div className="instructions">
        <p>
          This website was created to help you determine if an image is real or generated by an AI.<br/>
          Please upload the image you want to test from your desktop or Drag & Drop it here.
        </p>
      </div>
      <FileUploader
        multiple={false}
        handleChange={handleChange}
        name="file"
        types={fileTypes}
      />
      <p>{file ? `File name: ${file.name}` : "No file uploaded yet"}</p>
      {fileURL && (
        <img
          src={fileURL}
          alt="Preview"
          style={{ maxWidth: "100%", maxHeight: "300px", marginTop: "10px" }}
        />
      )}
      <div className="boutons">
        <Button
          disabled={disableButton}
          variant="contained"
          onClick={handleNavigateToResults}
          sx={{
            marginTop: "20px",
            backgroundColor: "#65b2a0",
            color: "#fff",
            "&:hover": { backgroundColor: "#386258" },
          }}
        >
          Analyse your image
        </Button>
        <Button
          variant="contained"
          onClick={() => navigate("/demo")}
          sx={{
            marginLeft: "10px",
            marginTop: "20px",
            backgroundColor: "#65b2a0",
            color: "#fff",
            "&:hover": { backgroundColor: "#386258" },
          }}
        >
          Try with test images
        </Button>
      </div>
    </div>
  );
};

export default Page;
