import { FileUploader } from "react-drag-drop-files";
import {MagnifyingGlass} from "react-loader-spinner";
import "./Page.css";
import { useState } from "react";
import { Button, Alert} from "@mui/material";
import DisplayCard from "./DisplayCard";

import axios from 'axios';
import { useNavigate } from "react-router-dom";

const fileTypes = ["JPG", "PNG", "WEBP"];

const Page = () => {
  const TypeAlertMessageEnum = {
    SuccessMessage: 'Given the accuracy, this result is very reliable!',
    InfoMessage: 'Given the accuracy, this result is fairly reliable',
    WarningMessage: 'Given the accuracy, this result may be uncertain',
    ErrorMessage: 'Given the accuracy, this result is uncertain'
  } as const
  const [file, setFile] = useState<File | null>(null);
  const [disableButton, setDisableButton] = useState(true);
  const [result, setResult] = useState("");
  const [accuracy, setAccuracy] = useState<number | null>(null);
  const [loading, setLoading] = useState(false);
  const [alertMessage, setAlertMessage] = useState("");
  const [fileURL, setFileURL] = useState<string | null>(null); // Pour stocker l'URL de l'image
  const [displayDragAndDropPage,setDisplayDragAndDropPage] = useState("DRAGANDDROP");
  const API_BASE_URL = 'http://192.168.37.156:50000/predict/image';
  const navigate = useNavigate();


  const handleChange = (file: File) => {
    setFile(file);
    setDisableButton(file == null);
    if (file) {
      const imageUrl = URL.createObjectURL(file);
      setFileURL(imageUrl);
    }
  };

  const handleDisplayDragAndDropPage = (value:string) => {
    setDisplayDragAndDropPage(value);
    if (value === "DRAGANDDROP") {
      setDisableButton(true);
      setFileURL(null);
      setFile(null);
      setResult("");
      setAccuracy(null);
      setLoading(false);
    } else {
        // On envoie l'image au modèle
        if (file) {
          setLoading(true);
          const formData = new FormData();
          formData.append('image', file);
  
          axios.post(
            API_BASE_URL,
            formData,
          {
            headers: {
              'Content-Type': 'multipart/form-data',
            },
          }
        ).then(function (response) {
          const data = response.data;
          if (data && typeof data === 'object') {
            if ('prediction' in data && 'confidence' in data) {
              const confidence = parseFloat(data.confidence.toFixed(2));
              setResult(data.prediction);
              setAccuracy(confidence);
              if (confidence <= 60) {
                setAlertMessage(TypeAlertMessageEnum.ErrorMessage)
              } else if (confidence > 60 && confidence <= 70) {
                setAlertMessage(TypeAlertMessageEnum.WarningMessage)
              } else if (confidence > 70 && confidence <= 85) {
                setAlertMessage(TypeAlertMessageEnum.InfoMessage)
              } else {
                setAlertMessage(TypeAlertMessageEnum.SuccessMessage)
              }
              if (result != null && accuracy != null){
                console.log("Réponse valide : ", data);
              } else {
                console.error("Réponse invalide : ", data);
              }
            } else {
              console.error("Clés manquantes dans la réponse : ", data);
            }
          } else {
            console.error('La réponse n\'est pas un objet JSON valide :', response);
          } 
        }).catch(function (error) {
          console.error('Error uploading file:', error);
        }).finally(() => {
          setLoading(false);
        });
      }

    }
  }

  return (
    <div className="page">
      {displayDragAndDropPage === "DRAGANDDROP" ? (
        <div>
          <div className="page">
            <div className="instructions">
              <p>This website was created to help you determine if an image is real or generated by an AI.<br/>
              Please upload the image you want to test from your desktop and Drag & Drop it here</p>
            </div>
            <FileUploader
              multiple={false}
              handleChange={handleChange}
              name="file"
              types={fileTypes}
            />
            <p>{file != null ? `File name: ${file.name}` : "No file uploaded yet"}</p>
            {fileURL && <img src={fileURL} alt="Preview" style={{ maxWidth: "100%", maxHeight: "300px" }} />}
          </div>
          <Button
            disabled={disableButton}
            variant="contained"
            onClick={() => handleDisplayDragAndDropPage("RESULTS")}
            sx={{
              marginTop:"20px",
              backgroundColor: "#65b2a0",
              color: "#fff",
              "&:hover": { backgroundColor: "#386258" },
            }}
          >
            Analyse your image
          </Button>
          <Button
            variant="contained"
            onClick={() => navigate("/demo")}
            sx={{
              marginLeft:"10px",
              marginTop:"20px",
              backgroundColor: "#65b2a0",
              color: "#fff",
              "&:hover": { backgroundColor: "#386258" },
            }}
          >
            Try with test images
          </Button>
        </div>
      ) : (
        <div className="page">
          {fileURL && <img src={fileURL} alt="Uploaded" style={{ maxWidth: "100%", maxHeight: "350px"}} />}
          <div className="card">
          {loading ? (
              <MagnifyingGlass color="#65b2a0"/>
            ) : (
              <div>
                <DisplayCard result={result} accuracy={accuracy} />
                {alertMessage === TypeAlertMessageEnum.ErrorMessage ? (
                <Alert severity='error' >{alertMessage}</Alert>
                ) : alertMessage === TypeAlertMessageEnum.WarningMessage ? (
                  <Alert severity='warning' >{alertMessage}</Alert>
                ) : alertMessage === TypeAlertMessageEnum.InfoMessage ? (
                  <Alert severity='info' >{alertMessage}</Alert>
                ) : (
                  <Alert severity='success' >{alertMessage}</Alert>
                )}
              </div>
            )}
            </div>
          <Button
          variant="contained"
          onClick={() => handleDisplayDragAndDropPage("DRAGANDDROP")}
          sx={{
            backgroundColor: "#65b2a0",
            color: "#fff",
            "&:hover": { backgroundColor: "#386258" },
          }}
          >
            Analyze an other image
          </Button>
        </div>
      )}
    </div>
  );
};

export default Page;
